export type ApiAuthType = "session" | "device_key" | "public" | "oauth";

export type ApiEndpoint = {
  id: string;
  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  path: string;
  title: string;
  description: string;
  auth: ApiAuthType;
  roles?: string[];
  query?: { name: string; description: string }[];
  headers?: { name: string; description: string }[];
  body?: Record<string, unknown>;
  response?: Record<string, unknown>;
  tags?: string[];
};

export type ApiCategory = {
  id: string;
  title: string;
  description: string;
  icon: string;
  endpoints: ApiEndpoint[];
};

export type ApiCatalog = {
  version: string;
  baseUrl: string;
  generatedAt: string;
  auth: {
    session: string;
    device: string;
    realtime: string;
  };
  categories: ApiCategory[];
  stats: { endpoints: number; categories: number };
};

export function buildApiCatalog(baseUrl: string): ApiCatalog {
  const base = baseUrl.replace(/\/$/, "");

  const categories: ApiCategory[] = [
    {
      id: "overview",
      title: "Overview & Realtime",
      description: "Authentication, live events, and API discovery",
      icon: "radio",
      endpoints: [
        {
          id: "catalog",
          method: "GET",
          path: "/api/catalog",
          title: "API catalog",
          description: "Machine-readable catalog of all Smart HR endpoints — same data powering this documentation UI.",
          auth: "public",
          response: {
            version: "1.0",
            baseUrl: "https://your-app.com",
            generatedAt: "2026-08-07T10:00:00.000Z",
            auth: { session: "…", device: "…", realtime: "…" },
            categories: [{ id: "auth", title: "Authentication", endpoints: [] }],
            stats: { endpoints: 95, categories: 14 },
          },
          tags: ["overview"],
        },
        {
          id: "events",
          method: "GET",
          path: "/api/events",
          title: "Realtime SSE stream",
          description:
            "Server-Sent Events for live dashboard updates. Sends initial dashboard_updated, then broadcasts domain events. Heartbeat every 25s.",
          auth: "session",
          headers: [{ name: "Accept", description: "text/event-stream" }],
          response: {
            type: "attendance_updated | leave_updated | payroll_updated | job_updated | employee_updated | notification_updated | …",
            data: { id: "…", action: "created" },
            timestamp: "2026-08-07T10:00:00.000Z",
          },
          tags: ["overview", "SSE", "realtime"],
        },
        {
          id: "nav-summary",
          method: "GET",
          path: "/api/nav/summary",
          title: "Navigation summary",
          description: "Badge counts and nav metadata for the signed-in user: notifications, pending leave, team preview, invite affordances.",
          auth: "session",
          response: {
            notificationCount: 3,
            notifications: [{ id: "n_001", title: "Leave approval needed", href: "/leave", read: false }],
            pendingLeaveCount: 2,
            teamMembers: [{ id: "emp_001", firstName: "Alex", lastName: "Johnson" }],
            teamOverflowCount: 5,
            canInvite: true,
            inviteHref: "/employees",
            messagesHref: "/messages",
          },
          tags: ["overview"],
        },
      ],
    },
    {
      id: "auth",
      title: "Authentication",
      description: "Login, signup, and session management",
      icon: "shield",
      endpoints: [
        {
          id: "auth-login",
          method: "POST",
          path: "/api/auth/login",
          title: "Sign in",
          description: "Authenticate with email and password. Sets HTTP-only smart-hr-session cookie used on all subsequent requests.",
          auth: "public",
          body: { email: "hr@smarthr.com", password: "password" },
          response: { success: true },
          tags: ["auth"],
        },
        {
          id: "auth-signup",
          method: "POST",
          path: "/api/auth/signup",
          title: "Sign up",
          description:
            "Create a trial company account with default department, payroll settings, and admin employee (EMP001). Password min 8 chars.",
          auth: "public",
          body: {
            firstName: "Jane",
            lastName: "Doe",
            email: "jane@company.com",
            password: "password123",
            plan: "trial",
          },
          response: { success: true, plan: "trial" },
          tags: ["auth"],
        },
        {
          id: "auth-logout",
          method: "POST",
          path: "/api/auth/logout",
          title: "Sign out",
          description: "Destroys the session cookie and redirects to /login (302, not JSON).",
          auth: "session",
          response: { redirect: "/login" },
          tags: ["auth"],
        },
      ],
    },
    {
      id: "attendance",
      title: "Attendance",
      description: "Web check-in, device punches, and kiosk integration",
      icon: "clock",
      endpoints: [
        {
          id: "attendance-check-in",
          method: "POST",
          path: "/api/attendance/check-in",
          title: "Web check-in",
          description: "Employee check-in from the dashboard. Requires session employeeId. Method recorded as WEB.",
          auth: "session",
          response: {
            success: true,
            id: "att_001",
            action: "check_in",
            status: "PRESENT",
            method: "WEB",
            checkIn: "2026-08-07T09:00:00.000Z",
            checkOut: null,
          },
          tags: ["attendance"],
        },
        {
          id: "attendance-check-out",
          method: "POST",
          path: "/api/attendance/check-out",
          title: "Web check-out",
          description: "Employee check-out from the dashboard. Returns 400 if no check-in exists for today.",
          auth: "session",
          response: { success: true, action: "check_out", status: "COMPLETED", method: "WEB" },
          tags: ["attendance"],
        },
        {
          id: "device-punch",
          method: "POST",
          path: "/api/attendance/device",
          title: "Device punch",
          description:
            "Record check-in, check-out, or auto-toggle from kiosk/biometric app. Identify employee by employeeCode, employeeId, or email. Idempotent via externalId.",
          auth: "device_key",
          headers: [{ name: "X-Device-Key", description: "Device API key from registration" }],
          body: {
            action: "toggle",
            employeeCode: "EMP001",
            timestamp: "2026-08-07T09:05:00.000Z",
            externalId: "device-event-12345",
          },
          response: { success: true, action: "check_in", status: "PRESENT", method: "DEVICE", duplicate: false },
          tags: ["device", "kiosk", "attendance"],
        },
        {
          id: "device-health",
          method: "GET",
          path: "/api/attendance/device",
          title: "Device ping & spec",
          description:
            "Without API key: public integration spec. With key: health check, last-seen update, device status, and supported actions.",
          auth: "device_key",
          headers: [{ name: "X-Device-Key", description: "Optional — enables device_connected mode" }],
          response: { ok: true, mode: "device_connected", device: { id: "dev_001", name: "Reception Kiosk" }, spec: {} },
          tags: ["device", "kiosk"],
        },
        {
          id: "device-sync",
          method: "POST",
          path: "/api/attendance/device/sync",
          title: "Batch device sync",
          description: "Replay offline punch events from mobile or kiosk storage. Returns per-event ok/error results.",
          auth: "device_key",
          body: {
            events: [{ action: "check_in", employeeCode: "EMP001", externalId: "offline-001", timestamp: "2026-08-07T08:00:00.000Z" }],
          },
          response: { success: true, processed: 1, results: [{ ok: true, duplicate: false }] },
          tags: ["device", "kiosk"],
        },
        {
          id: "device-docs",
          method: "GET",
          path: "/api/attendance/device/docs",
          title: "Device integration docs",
          description: "HR admin view: full spec, registered devices, online status, master key configuration.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: { ok: true, appUrl: "https://…", spec: {}, devices: [], masterKeyConfigured: false },
          tags: ["device"],
        },
        {
          id: "devices-list",
          method: "GET",
          path: "/api/attendance/devices",
          title: "List devices",
          description: "All registered attendance devices for the company with last-seen timestamps.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: { devices: [{ id: "dev_001", name: "Reception Kiosk", location: "Lobby", isActive: true, lastSeenAt: "2026-08-07T09:00:00.000Z" }] },
          tags: ["device"],
        },
        {
          id: "devices-create",
          method: "POST",
          path: "/api/attendance/devices",
          title: "Register device",
          description: "Create a kiosk/device and receive a one-time API key (shown only on create). Broadcasts attendance_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          body: { name: "Reception Kiosk", location: "Main lobby" },
          response: { device: { id: "dev_new", name: "Reception Kiosk", apiKey: "dev_…", isActive: true } },
          tags: ["device"],
        },
        {
          id: "devices-update",
          method: "PATCH",
          path: "/api/attendance/devices/:id",
          title: "Update device",
          description: "Rename, disable, or regenerate API key. Set regenerateKey: true to rotate key.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          body: { name: "Front desk kiosk", isActive: true, regenerateKey: false },
          response: { device: { id: "dev_001", name: "Front desk kiosk", isActive: true } },
          tags: ["device"],
        },
        {
          id: "devices-delete",
          method: "DELETE",
          path: "/api/attendance/devices/:id",
          title: "Delete device",
          description: "Remove a registered device permanently. Broadcasts attendance_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: { success: true },
          tags: ["device"],
        },
      ],
    },
    {
      id: "leave",
      title: "Leave",
      description: "Leave requests and approvals",
      icon: "calendar",
      endpoints: [
        {
          id: "leave-create",
          method: "POST",
          path: "/api/leave",
          title: "Submit leave request",
          description:
            "Employee submits a new leave request. Requires session employeeId. Notifies HR/managers. Broadcasts leave_updated.",
          auth: "session",
          body: { type: "ANNUAL", startDate: "2026-08-10", endDate: "2026-08-14", reason: "Vacation" },
          response: { success: true },
          tags: ["leave"],
        },
        {
          id: "leave-action",
          method: "PATCH",
          path: "/api/leave/:id",
          title: "Approve or reject",
          description: "Manager/HR approves or rejects a pending request. action must be approve or reject.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER", "SUPERVISOR"],
          body: { action: "approve" },
          response: { success: true },
          tags: ["leave"],
        },
      ],
    },
    {
      id: "employees",
      title: "Employees",
      description: "Workforce records and onboarding",
      icon: "users",
      endpoints: [
        {
          id: "employees-list",
          method: "GET",
          path: "/api/employees",
          title: "List employees",
          description: "Search and filter the employee directory. Returns department, manager, and user role.",
          auth: "session",
          query: [
            { name: "search", description: "Name, email, or employee code" },
            { name: "status", description: "ACTIVE | INACTIVE" },
            { name: "role", description: "COMPANY_ADMIN | HR | MANAGER | SUPERVISOR | EMPLOYEE" },
          ],
          response: [
            {
              id: "emp_001",
              employeeCode: "EMP001",
              firstName: "Alex",
              lastName: "Johnson",
              email: "alex@company.com",
              jobTitle: "Engineer",
              status: "ACTIVE",
              department: { id: "dept_001", name: "Engineering" },
              user: { role: "EMPLOYEE" },
            },
          ],
          tags: ["employees"],
        },
        {
          id: "employees-create",
          method: "POST",
          path: "/api/employees",
          title: "Create employee",
          description:
            "Onboard a new employee with optional welcome email. Returns 402 on subscription cap, 409 on duplicate email.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: {
            firstName: "Alex",
            lastName: "Johnson",
            email: "alex@company.com",
            jobTitle: "Engineer",
            departmentId: "dept_001",
            role: "EMPLOYEE",
            sendWelcomeEmail: true,
          },
          response: { success: true, employee: { id: "emp_new", employeeCode: "EMP025" }, emailSent: true },
          tags: ["employees"],
        },
        {
          id: "employees-get",
          method: "GET",
          path: "/api/employees/:id",
          title: "Get employee",
          description: "Single employee profile with department, manager, and role. Subject to canViewEmployee access.",
          auth: "session",
          response: {
            id: "emp_001",
            firstName: "Alex",
            lastName: "Johnson",
            department: { name: "Engineering" },
            manager: { firstName: "Jane", lastName: "Doe" },
            user: { role: "EMPLOYEE" },
          },
          tags: ["employees"],
        },
        {
          id: "employees-update",
          method: "PATCH",
          path: "/api/employees/:id",
          title: "Update employee",
          description: "Edit profile, job details, role, status, salary, department, or manager. Broadcasts employee_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { jobTitle: "Senior Engineer", departmentId: "dept_002", status: "ACTIVE" },
          response: { success: true, employee: { id: "emp_001", jobTitle: "Senior Engineer" } },
          tags: ["employees"],
        },
        {
          id: "employees-delete",
          method: "DELETE",
          path: "/api/employees/:id",
          title: "Deactivate employee",
          description: "Soft-delete: sets status to INACTIVE. Broadcasts employee_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["employees"],
        },
        {
          id: "employees-bulk",
          method: "PATCH",
          path: "/api/employees/bulk",
          title: "Bulk actions",
          description: "Bulk deactivate, activate, or department reassignment for selected employee IDs.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { ids: ["emp_001", "emp_002"], action: "set_department", departmentId: "dept_002" },
          response: { success: true, count: 2 },
          tags: ["employees"],
        },
      ],
    },
    {
      id: "payroll",
      title: "Payroll",
      description: "Pay runs, payslips, and compensation settings",
      icon: "wallet",
      endpoints: [
        {
          id: "payroll-list",
          method: "GET",
          path: "/api/payroll",
          title: "List payroll records",
          description: "Payroll cycles visible to the current user (role-scoped via payrollListWhere).",
          auth: "session",
          response: [{ id: "pay_001", employeeId: "emp_001", periodStart: "2026-08-01", periodEnd: "2026-08-31", status: "DRAFT", employee: { firstName: "Alex" } }],
          tags: ["payroll"],
        },
        {
          id: "payroll-create",
          method: "POST",
          path: "/api/payroll",
          title: "Create payroll run",
          description: "Generate payroll for a pay period with optional manual line items. Broadcasts payroll_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          body: { employeeId: "emp_001", periodStart: "2026-08-01", periodEnd: "2026-08-31", baseSalary: 5000, bonus: 200 },
          response: { id: "pay_new", status: "DRAFT", baseSalary: 5000, employee: { firstName: "Alex" } },
          tags: ["payroll"],
        },
        {
          id: "payroll-get",
          method: "GET",
          path: "/api/payroll/:id",
          title: "Get payroll record",
          description: "Single payslip with breakdown line items and canManage flag.",
          auth: "session",
          response: { id: "pay_001", breakdown: [{ label: "Base salary", amount: 5000 }], canManage: true },
          tags: ["payroll"],
        },
        {
          id: "payroll-update",
          method: "PATCH",
          path: "/api/payroll/:id",
          title: "Update payroll",
          description: "Edit line items, recalculate deductions, or change status. Set recalculate: true to rebuild auto breakdown.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          body: { recalculate: true, status: "APPROVED", notes: "Approved by HR" },
          response: { id: "pay_001", status: "APPROVED", breakdown: [] },
          tags: ["payroll"],
        },
        {
          id: "payroll-preview",
          method: "POST",
          path: "/api/payroll/preview",
          title: "Preview payroll",
          description: "Simulate payroll breakdown before saving — lateness, absence, tax, holiday allowance.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          body: { employeeId: "emp_001", periodStart: "2026-08-01", periodEnd: "2026-08-31", baseSalary: 5000 },
          response: { items: [{ label: "Base salary", amount: 5000 }], summary: { gross: 5000, deductions: 750, net: 4250 } },
          tags: ["payroll"],
        },
        {
          id: "payroll-settings",
          method: "GET",
          path: "/api/payroll/settings",
          title: "Payroll settings",
          description: "Tax rates, lateness rules, absence deductions, and holiday allowance configuration.",
          auth: "session",
          response: { taxRatePercent: 15, latenessDeductionPerDay: 50, holidayAllowanceEnabled: true, holidayAllowanceAmount: 100 },
          tags: ["payroll"],
        },
        {
          id: "payroll-settings-patch",
          method: "PATCH",
          path: "/api/payroll/settings",
          title: "Update settings",
          description: "Save payroll configuration. Broadcasts payroll_updated with action settings_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          body: { taxRatePercent: 15, latenessDeductionPerDay: 50, holidayAllowanceEnabled: true },
          response: { taxRatePercent: 15, latenessDeductionPerDay: 50 },
          tags: ["payroll"],
        },
        {
          id: "payroll-payslip",
          method: "GET",
          path: "/api/payroll/:id/payslip",
          title: "Download payslip",
          description: "HTML payslip download (Content-Type: text/html attachment), not PDF.",
          auth: "session",
          response: { note: "Binary HTML attachment — open in browser or save as .html" },
          tags: ["payroll"],
        },
        {
          id: "payroll-delete",
          method: "DELETE",
          path: "/api/payroll/:id",
          title: "Delete payroll",
          description: "Remove a payroll run permanently. HR/admin only.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: { success: true },
          tags: ["payroll"],
        },
      ],
    },
    {
      id: "recruitment",
      title: "Recruitment",
      description: "Jobs, candidates, interviews, and Google Calendar",
      icon: "briefcase",
      endpoints: [
        {
          id: "jobs-list",
          method: "GET",
          path: "/api/jobs",
          title: "List jobs",
          description: "Open and closed job postings with department and application counts.",
          auth: "session",
          response: [{ id: "job_001", title: "Senior Engineer", status: "OPEN", department: { name: "Engineering" }, _count: { applications: 12 } }],
          tags: ["recruitment"],
        },
        {
          id: "jobs-create",
          method: "POST",
          path: "/api/jobs",
          title: "Create job",
          description: "Post a new job opening with optional hiring team and custom pipeline stages.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { title: "Senior Engineer", departmentId: "dept_001", location: "Remote", type: "FULL_TIME", description: "…", requirements: "…" },
          response: { id: "job_new", title: "Senior Engineer", status: "OPEN" },
          tags: ["recruitment"],
        },
        {
          id: "jobs-get",
          method: "GET",
          path: "/api/jobs/:id",
          title: "Get job",
          description: "Single job with department and applications including assigned reviewer.",
          auth: "session",
          response: { id: "job_001", title: "Senior Engineer", applications: [{ id: "app_001", firstName: "Sam", pipelineStage: "Screening" }] },
          tags: ["recruitment"],
        },
        {
          id: "jobs-update",
          method: "PATCH",
          path: "/api/jobs/:id",
          title: "Update job",
          description: "Edit job details or status. CLOSED sets closedAt timestamp. Broadcasts job_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { status: "CLOSED" },
          response: { id: "job_001", status: "CLOSED", closedAt: "2026-08-07T10:00:00.000Z" },
          tags: ["recruitment"],
        },
        {
          id: "jobs-delete",
          method: "DELETE",
          path: "/api/jobs/:id",
          title: "Delete job",
          description: "Remove a job posting permanently.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["recruitment"],
        },
        {
          id: "applications-list",
          method: "GET",
          path: "/api/applications",
          title: "List applications",
          description: "Candidates across jobs. Filter by jobId, status, stage, or search term.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          query: [
            { name: "jobId", description: "Filter by job" },
            { name: "stage", description: "Pipeline stage name" },
            { name: "search", description: "Name or email" },
          ],
          response: [{ id: "app_001", firstName: "Sam", lastName: "Lee", pipelineStage: "Interview", job: { title: "Senior Engineer" } }],
          tags: ["recruitment"],
        },
        {
          id: "applications-create",
          method: "POST",
          path: "/api/applications",
          title: "Add candidate",
          description: "Add applicant to a job pipeline with optional source tag and resume URL.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { jobId: "job_001", firstName: "Sam", lastName: "Lee", email: "sam@email.com", source: "LinkedIn" },
          response: { id: "app_new", pipelineStage: "Applied", status: "ACTIVE" },
          tags: ["recruitment"],
        },
        {
          id: "applications-get",
          method: "GET",
          path: "/api/applications/:id",
          title: "Get application",
          description: "Full candidate profile with activities (50 latest), evaluations, and scheduled interviews.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { id: "app_001", activities: [], evaluations: [], interviews: [], job: { title: "Senior Engineer" } },
          tags: ["recruitment"],
        },
        {
          id: "applications-update",
          method: "PATCH",
          path: "/api/applications/:id",
          title: "Update application",
          description:
            "Move pipeline stage, assign reviewer, or edit details. Hired stage auto-onboards staff (default password, welcome email).",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { pipelineStage: "Hired", reason: "Offer accepted" },
          response: { id: "app_001", pipelineStage: "Hired" },
          tags: ["recruitment"],
        },
        {
          id: "applications-delete",
          method: "DELETE",
          path: "/api/applications/:id",
          title: "Delete application",
          description: "Remove a candidate from the pipeline.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["recruitment"],
        },
        {
          id: "applications-activities",
          method: "GET",
          path: "/api/applications/:id/activities",
          title: "Application activities",
          description: "Timeline of stage changes, notes, emails, and onboarding events.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: [{ id: "act_001", type: "STAGE_CHANGE", title: "Moved to Interview", createdAt: "2026-08-01T10:00:00.000Z" }],
          tags: ["recruitment"],
        },
        {
          id: "applications-activities-post",
          method: "POST",
          path: "/api/applications/:id/activities",
          title: "Log activity",
          description: "Add a manual note or activity entry to the candidate timeline.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { type: "NOTE", message: "Strong portfolio review" },
          response: { id: "act_new", type: "NOTE", message: "Strong portfolio review" },
          tags: ["recruitment"],
        },
        {
          id: "applications-evaluations",
          method: "POST",
          path: "/api/applications/:id/evaluations",
          title: "Submit evaluation",
          description: "Structured interviewer rating. Requires session employeeId as reviewer.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { rating: 4, feedback: "Strong technical skills" },
          response: { id: "eval_001", rating: 4, feedback: "Strong technical skills" },
          tags: ["recruitment"],
        },
        {
          id: "applications-email",
          method: "POST",
          path: "/api/applications/:id/email",
          title: "Send candidate email",
          description: "Compose templated email, log to activity feed. Returns preview of rendered subject/body.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { subject: "Interview invitation", body: "Hi {{candidate_first_name}}…", templateId: "tpl_001" },
          response: { success: true, preview: { subject: "Interview invitation", body: "Hi Sam…" } },
          tags: ["recruitment"],
        },
        {
          id: "recruitment-settings-get",
          method: "GET",
          path: "/api/recruitment/settings",
          title: "Recruitment settings",
          description: "Pipeline stages, tags, sources, and email templates for the company.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: { stages: [], tags: [], sources: [], templates: [] },
          tags: ["recruitment"],
        },
        {
          id: "recruitment-settings-post",
          method: "POST",
          path: "/api/recruitment/settings",
          title: "Create setting",
          description: "Add stage, tag, source, or email template.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          body: { type: "stage", name: "Final Interview", sortOrder: 4 },
          response: { id: "stage_new", name: "Final Interview", sortOrder: 4 },
          tags: ["recruitment"],
        },
        {
          id: "recruitment-settings-patch",
          method: "PATCH",
          path: "/api/recruitment/settings",
          title: "Update setting",
          description: "Edit stage or email template by type and id.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          body: { type: "stage", id: "stage_001", name: "Final Round" },
          response: { id: "stage_001", name: "Final Round" },
          tags: ["recruitment"],
        },
        {
          id: "recruitment-settings-delete",
          method: "DELETE",
          path: "/api/recruitment/settings",
          title: "Delete setting",
          description: "Remove stage, tag, source, or template.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          query: [
            { name: "type", description: "stage | tag | source | template" },
            { name: "id", description: "Record ID" },
          ],
          response: { success: true },
          tags: ["recruitment"],
        },
        {
          id: "interviews-list",
          method: "GET",
          path: "/api/interviews",
          title: "List interviews",
          description: "Scheduled interviews. Filter by status or applicationId.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          query: [
            { name: "status", description: "SCHEDULED | COMPLETED | CANCELLED" },
            { name: "applicationId", description: "Filter by candidate" },
          ],
          response: [{ id: "int_001", scheduledAt: "2026-08-10T14:00:00.000Z", status: "SCHEDULED", application: { firstName: "Sam" } }],
          tags: ["recruitment"],
        },
        {
          id: "interviews-get",
          method: "GET",
          path: "/api/interviews/:id",
          title: "Get interview",
          description: "Interview details with application, interviewer, and submitted reviews.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { id: "int_001", meetLink: "https://meet.google.com/…", reviews: [] },
          tags: ["recruitment"],
        },
        {
          id: "interviews-create",
          method: "POST",
          path: "/api/interviews",
          title: "Schedule interview",
          description: "Create interview with optional Google Meet link when Calendar is connected.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { applicationId: "app_001", interviewerId: "emp_002", scheduledAt: "2026-08-10T14:00:00.000Z", type: "VIDEO" },
          response: { id: "int_new", status: "SCHEDULED", meetLink: "https://meet.google.com/…" },
          tags: ["recruitment"],
        },
        {
          id: "interviews-update",
          method: "PATCH",
          path: "/api/interviews/:id",
          title: "Update interview",
          description: "Reschedule fields or cancel with { action: 'cancel' }. Broadcasts interview_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { action: "cancel" },
          response: { id: "int_001", status: "CANCELLED" },
          tags: ["recruitment"],
        },
        {
          id: "interview-reviews",
          method: "POST",
          path: "/api/interviews/:id/reviews",
          title: "Submit review",
          description: "Interviewer feedback and score. Marks interview COMPLETED if still SCHEDULED.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { rating: 4, recommendation: "HIRE", strengths: "Communication", notes: "…" },
          response: { id: "rev_001", rating: 4, recommendation: "HIRE" },
          tags: ["recruitment"],
        },
        {
          id: "google-auth",
          method: "GET",
          path: "/api/google/auth",
          title: "Google OAuth",
          description: "Start Google Calendar connection for interview scheduling.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { redirect: "https://accounts.google.com/o/oauth2/v2/auth?…" },
          tags: ["recruitment", "oauth"],
        },
        {
          id: "google-callback",
          method: "GET",
          path: "/api/google/callback",
          title: "Google OAuth callback",
          description: "OAuth redirect handler — stores Calendar tokens and redirects to recruitment settings.",
          auth: "oauth",
          query: [{ name: "code", description: "Authorization code" }, { name: "state", description: "CSRF state" }],
          response: { redirect: "/recruitment/settings?google=connected" },
          tags: ["recruitment", "oauth"],
        },
        {
          id: "google-status",
          method: "GET",
          path: "/api/google/status",
          title: "Google status",
          description: "Calendar connection state for the signed-in user.",
          auth: "session",
          response: { connected: true, email: "hr@company.com" },
          tags: ["recruitment"],
        },
      ],
    },
    {
      id: "performance",
      title: "Performance",
      description: "KPIs, appraisal cycles, and reviews",
      icon: "medal",
      endpoints: [
        {
          id: "kpis-list",
          method: "GET",
          path: "/api/performance/kpis",
          title: "List KPIs",
          description: "Active KPI definitions library with optional department scope.",
          auth: "session",
          response: [{ id: "kpi_001", title: "Sales quota", targetValue: 100, weight: 30, isActive: true }],
          tags: ["performance"],
        },
        {
          id: "kpis-create",
          method: "POST",
          path: "/api/performance/kpis",
          title: "Create KPI",
          description: "Add a measurable KPI to the library.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { title: "Customer satisfaction", targetValue: 90, weight: 25, metricType: "PERCENTAGE" },
          response: { id: "kpi_new", title: "Customer satisfaction", isActive: true },
          tags: ["performance"],
        },
        {
          id: "kpis-update",
          method: "PATCH",
          path: "/api/performance/kpis/:id",
          title: "Update KPI",
          description: "Edit KPI definition or deactivate.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { title: "Updated KPI", weight: 35, isActive: true },
          response: { id: "kpi_001", title: "Updated KPI", weight: 35 },
          tags: ["performance"],
        },
        {
          id: "kpis-delete",
          method: "DELETE",
          path: "/api/performance/kpis/:id",
          title: "Delete KPI",
          description: "Soft-delete: sets isActive to false.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["performance"],
        },
        {
          id: "cycles-list",
          method: "GET",
          path: "/api/performance/cycles",
          title: "List cycles",
          description: "Appraisal cycles with linked KPIs and appraisal counts.",
          auth: "session",
          response: [{ id: "cyc_001", name: "H1 2026", status: "DRAFT", _count: { appraisals: 24 } }],
          tags: ["performance"],
        },
        {
          id: "cycles-get",
          method: "GET",
          path: "/api/performance/cycles/:id",
          title: "Get cycle",
          description: "Cycle with linked KPIs and all appraisals including employee and manager.",
          auth: "session",
          response: { id: "cyc_001", kpis: [], appraisals: [{ id: "apr_001", status: "SELF_REVIEW", employee: { firstName: "Alex" } }] },
          tags: ["performance"],
        },
        {
          id: "cycles-create",
          method: "POST",
          path: "/api/performance/cycles",
          title: "Create cycle",
          description: "Start a new review cycle. Optionally includeAllEmployees to auto-create appraisals.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { name: "H1 2026", period: "H1", startDate: "2026-01-01", endDate: "2026-06-30", includeAllEmployees: true, kpiIds: ["kpi_001"] },
          response: { id: "cyc_new", name: "H1 2026", status: "DRAFT" },
          tags: ["performance"],
        },
        {
          id: "cycles-update",
          method: "PATCH",
          path: "/api/performance/cycles/:id",
          title: "Update cycle",
          description: "Edit cycle metadata or run action activate/close to change status.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { action: "activate" },
          response: { id: "cyc_001", status: "ACTIVE" },
          tags: ["performance"],
        },
        {
          id: "appraisals-get",
          method: "GET",
          path: "/api/performance/appraisals/:id",
          title: "Get appraisal",
          description: "Single appraisal with canEditSelf and canEditManager flags for UI.",
          auth: "session",
          response: { id: "apr_001", status: "SELF_REVIEW", canEditSelf: true, canEditManager: false, kpiScores: [] },
          tags: ["performance"],
        },
        {
          id: "appraisals-update",
          method: "PATCH",
          path: "/api/performance/appraisals/:id",
          title: "Update appraisal",
          description: "Self or manager review scores. Set submit: true to advance status (SELF → MANAGER_REVIEW → COMPLETED).",
          auth: "session",
          body: { section: "self", selfRating: 4, selfComments: "Met all goals", submit: true },
          response: { id: "apr_001", status: "MANAGER_REVIEW", selfRating: 4 },
          tags: ["performance"],
        },
        {
          id: "reviews-list",
          method: "GET",
          path: "/api/performance",
          title: "List legacy reviews",
          description: "Legacy performance review records. Role-scoped: employees see own, managers see team.",
          auth: "session",
          response: [{ id: "rev_001", period: "2025", rating: 4, employee: { firstName: "Alex" }, status: "COMPLETED" }],
          tags: ["performance"],
        },
        {
          id: "reviews-create",
          method: "POST",
          path: "/api/performance",
          title: "Create legacy review",
          description: "Create a standalone performance review record (legacy flow).",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { employeeId: "emp_001", period: "2025", goals: "Increase output by 10%" },
          response: { id: "rev_new", period: "2025", status: "DRAFT" },
          tags: ["performance"],
        },
        {
          id: "reviews-update",
          method: "PATCH",
          path: "/api/performance/:id",
          title: "Update legacy review",
          description: "Edit goals, feedback, rating, or status on a legacy performance review.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { rating: 4, status: "COMPLETED", feedback: "Exceeded expectations" },
          response: { id: "rev_001", rating: 4, status: "COMPLETED" },
          tags: ["performance"],
        },
        {
          id: "reviews-delete",
          method: "DELETE",
          path: "/api/performance/:id",
          title: "Delete legacy review",
          description: "Permanently remove a legacy performance review.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["performance"],
        },
      ],
    },
    {
      id: "organization",
      title: "Organization",
      description: "Departments, holidays, announcements, and HR documents — all company-scoped",
      icon: "building",
      endpoints: [
        {
          id: "departments-list",
          method: "GET",
          path: "/api/departments",
          title: "List departments",
          description:
            "Returns departments for the signed-in user's company with employee and job counts. Super admin sees all tenants.",
          auth: "session",
          response: [
            {
              id: "dept_001",
              companyId: "co_001",
              name: "Engineering",
              description: "Software development",
              createdAt: "2026-01-15T08:00:00.000Z",
              _count: { employees: 24, jobs: 3 },
            },
          ],
          tags: ["organization"],
        },
        {
          id: "departments-get",
          method: "GET",
          path: "/api/departments/:id",
          title: "Get department",
          description:
            "Single department with employees (incl. role), recent jobs (latest 10), and counts. Used by department and team detail pages.",
          auth: "session",
          response: {
            id: "dept_001",
            name: "Engineering",
            description: "Software development",
            employees: [{ id: "emp_001", firstName: "Alex", lastName: "Johnson", user: { role: "EMPLOYEE" } }],
            jobs: [{ id: "job_001", title: "Senior Engineer", status: "OPEN" }],
            _count: { employees: 24, jobs: 3 },
          },
          tags: ["organization"],
        },
        {
          id: "departments-create",
          method: "POST",
          path: "/api/departments",
          title: "Create department",
          description:
            "Creates a department/team for the current company. Name must be unique per company. Broadcasts department_updated SSE event.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { name: "Product", description: "Product management and design" },
          response: {
            id: "dept_new",
            name: "Product",
            description: "Product management and design",
            companyId: "co_001",
            _count: { employees: 0, jobs: 0 },
          },
          tags: ["organization"],
        },
        {
          id: "departments-update",
          method: "PATCH",
          path: "/api/departments/:id",
          title: "Update department",
          description: "Edit name or description. Requires canManageDepartments (COMPANY_ADMIN, HR, MANAGER).",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { name: "Product & Design", description: "Updated description" },
          response: { id: "dept_001", name: "Product & Design", _count: { employees: 5, jobs: 1 } },
          tags: ["organization"],
        },
        {
          id: "departments-delete",
          method: "DELETE",
          path: "/api/departments/:id",
          title: "Delete department",
          description:
            "Permanently removes a department. Returns 400 if any employees are still assigned — reassign staff first.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["organization"],
        },
        {
          id: "holidays-list",
          method: "GET",
          path: "/api/holidays",
          title: "List holidays",
          description:
            "Company calendar entries sorted by date. Scoped to session companyId. Returns 503 if Holiday model is unavailable (run prisma generate).",
          auth: "session",
          response: [
            {
              id: "hol_001",
              companyId: "co_001",
              name: "New Year's Day",
              date: "2026-01-01T00:00:00.000Z",
              type: "Public",
              createdAt: "2026-01-01T00:00:00.000Z",
            },
          ],
          tags: ["organization"],
        },
        {
          id: "holidays-create",
          method: "POST",
          path: "/api/holidays",
          title: "Create holiday",
          description:
            "Adds a company holiday. Used by payroll (holiday allowance) and the attendance calendar. Broadcasts holiday_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { name: "Company Day", date: "2026-12-24", type: "Public" },
          response: {
            id: "hol_new",
            name: "Company Day",
            date: "2026-12-24T00:00:00.000Z",
            type: "Public",
            companyId: "co_001",
          },
          tags: ["organization"],
        },
        {
          id: "holidays-update",
          method: "PATCH",
          path: "/api/holidays/:id",
          title: "Update holiday",
          description: "Edit name, date (ISO string), or type (e.g. Public, Company, Optional).",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { name: "Christmas Eve", date: "2026-12-24", type: "Company" },
          response: { id: "hol_001", name: "Christmas Eve", type: "Company" },
          tags: ["organization"],
        },
        {
          id: "holidays-delete",
          method: "DELETE",
          path: "/api/holidays/:id",
          title: "Delete holiday",
          description: "Removes a calendar entry. Broadcasts holiday_updated SSE event.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["organization"],
        },
        {
          id: "announcements-list",
          method: "GET",
          path: "/api/announcements",
          title: "List announcements",
          description: "Company news feed, newest first. Scoped to session companyId.",
          auth: "session",
          response: [
            {
              id: "ann_001",
              companyId: "co_001",
              title: "Q3 all-hands",
              content: "Join us Friday at 3pm in the main hall.",
              author: "HR Admin",
              priority: "NORMAL",
              createdAt: "2026-08-01T10:00:00.000Z",
            },
          ],
          tags: ["organization"],
        },
        {
          id: "announcements-create",
          method: "POST",
          path: "/api/announcements",
          title: "Create announcement",
          description:
            "Publishes a company update. Sends in-app notifications to all company users. Broadcasts announcement_created. Appears on dashboard feed.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: {
            title: "Office closed Monday",
            content: "The office will be closed for maintenance.",
            priority: "HIGH",
          },
          response: {
            id: "ann_new",
            title: "Office closed Monday",
            content: "The office will be closed for maintenance.",
            author: "Jane Doe",
            priority: "HIGH",
            companyId: "co_001",
          },
          tags: ["organization"],
        },
        {
          id: "announcements-update",
          method: "PATCH",
          path: "/api/announcements/:id",
          title: "Update announcement",
          description: "Edit title, content, or priority (NORMAL | HIGH | URGENT).",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: { title: "Updated title", priority: "URGENT" },
          response: { id: "ann_001", title: "Updated title", priority: "URGENT" },
          tags: ["organization"],
        },
        {
          id: "announcements-delete",
          method: "DELETE",
          path: "/api/announcements/:id",
          title: "Delete announcement",
          description: "Removes an announcement from the feed.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["organization"],
        },
        {
          id: "documents-list",
          method: "GET",
          path: "/api/documents",
          title: "List documents",
          description:
            "HR document library. Employees see company-wide docs (employeeId null) plus their own; HR/admins see all. Includes linked employee profile when scoped.",
          auth: "session",
          response: [
            {
              id: "doc_001",
              title: "Employee Handbook 2026",
              category: "Policy",
              fileUrl: "https://storage.example.com/handbook.pdf",
              uploadedBy: "HR Admin",
              employeeId: null,
              employee: null,
              createdAt: "2026-01-10T09:00:00.000Z",
            },
          ],
          tags: ["organization"],
        },
        {
          id: "documents-upload",
          method: "POST",
          path: "/api/documents",
          title: "Upload document",
          description:
            "Creates a document record with metadata. fileUrl is an external link (no binary upload in this endpoint). Set employeeId to attach to a specific employee, or omit for company-wide docs. HR/admin only.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          body: {
            title: "Offer Letter — Alex Johnson",
            category: "Contract",
            fileUrl: "https://storage.example.com/offer.pdf",
            employeeId: "emp_001",
          },
          response: {
            id: "doc_new",
            title: "Offer Letter — Alex Johnson",
            category: "Contract",
            fileUrl: "https://storage.example.com/offer.pdf",
            uploadedBy: "Jane Doe",
            employeeId: "emp_001",
          },
          tags: ["organization"],
        },
        {
          id: "documents-delete",
          method: "DELETE",
          path: "/api/documents/:id",
          title: "Delete document",
          description: "Removes document metadata record. Does not delete external file at fileUrl. HR/admin only.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "MANAGER"],
          response: { success: true },
          tags: ["organization"],
        },
      ],
    },
    {
      id: "integrations",
      title: "Integrations",
      description: "OAuth connections, sync jobs, webhooks, and third-party apps (Google Workspace & Zoho)",
      icon: "plug",
      endpoints: [
        {
          id: "integrations-list",
          method: "GET",
          path: "/api/integrations",
          title: "List integrations",
          description:
            "Returns every provider in the catalog with connection state, OAuth readiness, webhook paths, and the 20 most recent sync log entries for the signed-in company.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: {
            items: [
              {
                provider: "GOOGLE_WORKSPACE",
                slug: "google-workspace",
                name: "Google Workspace",
                vendor: "Google",
                description: "Calendar, Gmail, Directory, Drive, and Meet",
                modules: ["Calendar", "Gmail", "Directory", "Drive", "Meet"],
                webhookPath: "/api/webhooks/google",
                docsUrl: "https://developers.google.com/workspace",
                configured: true,
                status: "CONNECTED",
                connected: true,
                accountEmail: "admin@company.com",
                lastSyncAt: "2026-08-07T10:00:00.000Z",
                lastError: null,
                connectedAt: "2026-08-01T09:00:00.000Z",
                webhookSecret: "whsec_…",
              },
            ],
            logs: [
              {
                id: "…",
                provider: "ZOHO_PEOPLE",
                direction: "inbound",
                eventType: "full_sync",
                summary: "Synced 12 employees from Zoho People",
                status: "SUCCESS",
                createdAt: "2026-08-07T10:00:00.000Z",
              },
            ],
          },
          tags: ["integrations"],
        },
        {
          id: "integrations-connect",
          method: "GET",
          path: "/api/integrations/:slug/connect",
          title: "Connect integration (OAuth start)",
          description:
            "Starts the OAuth flow for a provider. Responds with HTTP 302 redirect to Google or Zoho. State is base64url-encoded JSON containing userId and companyId. Requires OAuth app credentials in .env.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          query: [
            { name: "slug", description: "google-workspace | zoho-people | zoho-recruit | zoho-books | zoho-sign | zoho-mail" },
          ],
          response: { redirect: "https://accounts.google.com/o/oauth2/v2/auth?…" },
          tags: ["integrations", "oauth"],
        },
        {
          id: "integrations-callback",
          method: "GET",
          path: "/api/integrations/:slug/callback",
          title: "OAuth callback",
          description:
            "Provider redirect URI. Exchanges authorization code for tokens, stores them per company, runs an initial sync, then redirects to /settings/integrations?connected={slug}.",
          auth: "oauth",
          query: [
            { name: "code", description: "Authorization code from provider" },
            { name: "state", description: "Base64url JSON: { userId, companyId }" },
            { name: "error", description: "Provider error code (denied access)" },
          ],
          response: { redirect: "/settings/integrations?connected=google-workspace" },
          tags: ["integrations", "oauth"],
        },
        {
          id: "integrations-get",
          method: "GET",
          path: "/api/integrations/:slug",
          title: "Integration status",
          description: "Connection details for one provider including sync timestamps, errors, and webhook secret.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          query: [{ name: "slug", description: "Provider slug (see connect endpoint)" }],
          response: {
            provider: "ZOHO_PEOPLE",
            slug: "zoho-people",
            configured: true,
            status: "CONNECTED",
            connected: true,
            accountEmail: "hr@company.com",
            lastSyncAt: "2026-08-07T09:30:00.000Z",
            lastError: null,
            connectedAt: "2026-08-01T08:00:00.000Z",
            webhookSecret: "whsec_…",
          },
          tags: ["integrations"],
        },
        {
          id: "integrations-delete",
          method: "DELETE",
          path: "/api/integrations/:slug",
          title: "Disconnect",
          description:
            "Revokes stored tokens and marks the integration DISCONNECTED. Google Workspace uses a dedicated disconnect path. Broadcasts integration_updated SSE event.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: { success: true },
          tags: ["integrations"],
        },
        {
          id: "integrations-sync",
          method: "POST",
          path: "/api/integrations/:slug/sync",
          title: "Sync integration",
          description:
            "Runs a full sync for one connected provider. Marks status SYNCING → CONNECTED on success, or ERROR with lastError on failure. Broadcasts integration_sync SSE event.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: {
            success: true,
            synced: 12,
            summary: "Synced 12 employees from Zoho People",
          },
          tags: ["integrations"],
        },
        {
          id: "integrations-sync-all",
          method: "POST",
          path: "/api/integrations/sync-all",
          title: "Sync all connected",
          description:
            "Iterates every provider; skips disconnected ones. Returns per-provider ok/summary. Broadcasts integration_sync with action sync_all.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR"],
          response: {
            success: true,
            results: [
              { provider: "GOOGLE_WORKSPACE", ok: true, summary: "Google Workspace connected — calendar push active" },
              { provider: "ZOHO_PEOPLE", ok: true, summary: "Synced 5 employees from Zoho People" },
              { provider: "ZOHO_RECRUIT", ok: false },
            ],
          },
          tags: ["integrations"],
        },
        {
          id: "integrations-cron",
          method: "POST",
          path: "/api/integrations/cron",
          title: "Cron sync (all tenants)",
          description:
            "Background job endpoint for scheduled sync across all companies. Protected by x-cron-secret header matching INTEGRATION_CRON_SECRET in .env. If secret is unset, endpoint is open (dev only).",
          auth: "public",
          headers: [{ name: "x-cron-secret", description: "Must match INTEGRATION_CRON_SECRET in .env" }],
          response: {
            success: true,
            at: "2026-08-07T10:00:00.000Z",
            results: [{ provider: "ZOHO_PEOPLE", ok: true, summary: "Synced 3 employees" }],
          },
          tags: ["integrations", "cron"],
        },
      ],
    },
    {
      id: "notifications",
      title: "Notifications",
      description: "In-app alerts and read state",
      icon: "bell",
      endpoints: [
        {
          id: "notifications-list",
          method: "GET",
          path: "/api/notifications",
          title: "List notifications",
          description: "Unread and read in-app notifications for the current user with unread count.",
          auth: "session",
          response: {
            items: [{ id: "n_001", type: "leave", title: "Leave approval needed", message: "Alex requested annual leave", href: "/leave", read: false }],
            unread: 3,
          },
          tags: ["notifications"],
        },
        {
          id: "notifications-mark-read",
          method: "PATCH",
          path: "/api/notifications/:id",
          title: "Mark as read",
          description: "Mark one notification read. Broadcasts notification_updated.",
          auth: "session",
          response: { success: true },
          tags: ["notifications"],
        },
        {
          id: "notifications-mark-all",
          method: "PATCH",
          path: "/api/notifications",
          title: "Mark all read",
          description: "Clear unread badge for all notifications.",
          auth: "session",
          body: { all: true },
          response: { success: true },
          tags: ["notifications"],
        },
      ],
    },
    {
      id: "admin",
      title: "Admin & Billing",
      description: "Multi-tenant company admin and subscriptions",
      icon: "credit",
      endpoints: [
        {
          id: "subscription-get",
          method: "GET",
          path: "/api/subscription",
          title: "Subscription",
          description: "Current plan, trial status, employee limits, and whether new employees can be added.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "HR", "SUPER_ADMIN"],
          response: {
            planId: "pro",
            planName: "Pro",
            status: "ACTIVE",
            maxEmployees: 100,
            employeeCount: 42,
            trialEndsAt: null,
            canAddEmployees: true,
          },
          tags: ["admin"],
        },
        {
          id: "subscription-update",
          method: "PATCH",
          path: "/api/subscription",
          title: "Change plan",
          description: "Upgrade or downgrade subscription for the current company. Broadcasts subscription_updated.",
          auth: "session",
          roles: ["COMPANY_ADMIN", "SUPER_ADMIN"],
          body: { planId: "pro", billingEmail: "billing@company.com" },
          response: { planId: "pro", planName: "Pro", status: "ACTIVE" },
          tags: ["admin"],
        },
        {
          id: "admin-companies",
          method: "PATCH",
          path: "/api/admin/companies/:id",
          title: "Manage company",
          description: "Super admin: suspend tenant, change plan, or update billing email.",
          auth: "session",
          roles: ["SUPER_ADMIN"],
          body: { planId: "pro", subscriptionStatus: "ACTIVE", isActive: true, billingEmail: "billing@tenant.com" },
          response: { companyId: "co_001", planId: "pro", status: "ACTIVE" },
          tags: ["admin"],
        },
      ],
    },
    {
      id: "webhooks",
      title: "Webhooks",
      description: "Inbound push events from Google Workspace and Zoho — verify secrets, trigger syncs, broadcast SSE",
      icon: "webhook",
      endpoints: [
        {
          id: "webhook-google",
          method: "POST",
          path: "/api/webhooks/google",
          title: "Google Workspace webhook",
          description:
            "Receives Google Calendar push notifications. Validates x-goog-channel-token against the integration webhookSecret. Parses JSON body or falls back to x-goog-resource-* headers. Broadcasts holiday_updated and logs sync activity.",
          auth: "public",
          headers: [{ name: "x-goog-channel-token", description: "Must match integration webhookSecret" }],
          body: { resourceState: "sync", resourceId: "…", channelId: "…" },
          response: { ok: true },
          tags: ["integrations", "webhook"],
        },
        {
          id: "webhook-google-get",
          method: "GET",
          path: "/api/webhooks/google",
          title: "Google webhook verification",
          description: "Same handler as POST — used for Google channel verification pings.",
          auth: "public",
          tags: ["integrations", "webhook"],
        },
        {
          id: "webhook-zoho",
          method: "POST",
          path: "/api/webhooks/zoho/:product",
          title: "Zoho webhook",
          description:
            "Inbound events from Zoho People, Recruit, Books, Sign, or Mail. Validates x-zoho-webhook-signature. Triggers a follow-up sync and broadcasts domain events (employee_updated, job_updated, payroll_updated, etc.).",
          auth: "public",
          headers: [{ name: "x-zoho-webhook-signature", description: "Must match integration webhookSecret" }],
          query: [{ name: "product", description: "people | recruit | books | sign | mail" }],
          body: { event: "employee.updated", recordId: "12345" },
          response: { ok: true },
          tags: ["integrations", "webhook"],
        },
      ],
    },
    {
      id: "utility",
      title: "Search & Settings",
      description: "Global search, profile, and exports",
      icon: "search",
      endpoints: [
        {
          id: "search",
          method: "GET",
          path: "/api/search",
          title: "Global search",
          description: "Search employees, documents, jobs, announcements, and holidays. Jobs hidden for EMPLOYEE role.",
          auth: "session",
          query: [{ name: "q", description: "Search query (required for results)" }],
          response: {
            employees: [{ id: "emp_001", firstName: "Alex", lastName: "Johnson" }],
            documents: [],
            jobs: [{ id: "job_001", title: "Senior Engineer" }],
            announcements: [],
            holidays: [],
          },
          tags: ["utility"],
        },
        {
          id: "settings-profile",
          method: "PATCH",
          path: "/api/settings/profile",
          title: "Update profile",
          description: "Update phone, address, and notification preferences stored on the user record.",
          auth: "session",
          body: { phone: "+1 555 0100", address: "123 Main St", preferences: { emailDigest: true } },
          response: { success: true },
          tags: ["utility"],
        },
        {
          id: "dashboard-export",
          method: "GET",
          path: "/api/dashboard/export",
          title: "Export data",
          description: "CSV download. Types: employees, attendance (requires date), dashboard (requires range).",
          auth: "session",
          query: [
            { name: "type", description: "employees | attendance | dashboard (default)" },
            { name: "range", description: "week | month | quarter (dashboard only)" },
            { name: "date", description: "ISO date YYYY-MM-DD (attendance only)" },
          ],
          response: { note: "text/csv attachment download" },
          tags: ["utility"],
        },
      ],
    },
  ];

  const endpoints = categories.flatMap((c) => c.endpoints);

  return {
    version: "1.0",
    baseUrl: base,
    generatedAt: new Date().toISOString(),
    auth: {
      session: "HTTP-only cookie smart-hr-session — obtain via POST /api/auth/login",
      device: "Header X-Device-Key or Authorization: Bearer <key> — register at /attendance/devices",
      realtime: "GET /api/events (SSE) — events: attendance_updated, device_ping, leave_updated, payroll_updated, …",
    },
    categories,
    stats: { endpoints: endpoints.length, categories: categories.length },
  };
}

export function flattenEndpoints(catalog: ApiCatalog) {
  return catalog.categories.flatMap((cat) =>
    cat.endpoints.map((ep) => ({ ...ep, category: cat.id, categoryTitle: cat.title }))
  );
}
