import type { Role } from "@prisma/client";
import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Bell,
  Search,
  Calendar,
  Users,
  Network,
  UsersRound,
  CalendarOff,
  Clock,
  Wallet,
  Medal,
  GraduationCap,
  Briefcase,
  UserSearch,
  CalendarClock,
  Megaphone,
  FileText,
  CircleHelp,
  Settings,
  Plug2,
  Router,
  Building2,
  BookOpen,
  CreditCard,
  ListTodo,
  UserMinus,
} from "lucide-react";
import {
  ALL_STAFF,
  CONTENT_ADMIN_ROLES,
  DEVICE_ADMIN_ROLES,
  DASHBOARD_ROLES,
  INTEGRATION_ADMIN_ROLES,
  ONBOARDING_ROLES,
  ORG_CHART_ROLES,
  PAYROLL_VIEW_ROLES,
  PEOPLE_VIEW_ROLES,
  PERFORMANCE_VIEW_ROLES,
  RECRUITMENT_ROLES,
  SETTINGS_ROLES,
  SUBSCRIPTION_ADMIN_ROLES,
  SUPER_ADMIN_ONLY,
  hasRole,
} from "@/lib/roles";

export type AppFeature = {
  id: string;
  label: string;
  description: string;
  href: string;
  section: string;
  icon: LucideIcon;
  roles: Role[];
  helpSlug?: string;
};

/** Canonical list of in-app modules — used for nav, help directory, and cross-links. */
export const appFeatures: AppFeature[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    description: "Role-based overview, metrics, and upcoming events",
    href: "/dashboard",
    section: "Main",
    icon: LayoutDashboard,
    roles: DASHBOARD_ROLES,
    helpSlug: "getting-started",
  },
  {
    id: "companies",
    label: "Companies",
    description: "Multi-tenant company directory (platform admin)",
    href: "/admin/companies",
    section: "Main",
    icon: Building2,
    roles: SUPER_ADMIN_ONLY,
  },
  {
    id: "notifications",
    label: "Notifications",
    description: "Leave, payroll, announcements, and review alerts",
    href: "/notifications",
    section: "Main",
    icon: Bell,
    roles: ALL_STAFF,
  },
  {
    id: "search",
    label: "Search",
    description: "Find employees, jobs, documents, and records",
    href: "/search",
    section: "Main",
    icon: Search,
    roles: ALL_STAFF,
    helpSlug: "search",
  },
  {
    id: "calendar",
    label: "Calendar",
    description: "Company holidays and attendance calendar",
    href: "/holidays",
    section: "Main",
    icon: Calendar,
    roles: ALL_STAFF,
    helpSlug: "calendar",
  },
  {
    id: "employees",
    label: "Employees",
    description: "Directory, profiles, and employee records",
    href: "/employees",
    section: "People",
    icon: Users,
    roles: PEOPLE_VIEW_ROLES,
    helpSlug: "employees",
  },
  {
    id: "org-chart",
    label: "Org Chart",
    description: "Departments and reporting structure",
    href: "/departments",
    section: "People",
    icon: Network,
    roles: ORG_CHART_ROLES,
    helpSlug: "departments",
  },
  {
    id: "teams",
    label: "Teams",
    description: "Team views by department",
    href: "/teams",
    section: "People",
    icon: UsersRound,
    roles: PEOPLE_VIEW_ROLES,
    helpSlug: "teams",
  },
  {
    id: "onboarding",
    label: "Onboarding",
    description: "Track new-hire checklist progress and tasks",
    href: "/checklist/onboarding",
    section: "People",
    icon: GraduationCap,
    roles: ONBOARDING_ROLES,
    helpSlug: "employees",
  },
  {
    id: "offboarding",
    label: "Offboarding",
    description: "Manage employee exit checklists",
    href: "/checklist/offboarding",
    section: "People",
    icon: UserMinus,
    roles: ONBOARDING_ROLES,
    helpSlug: "employees",
  },
  {
    id: "checklist-todos",
    label: "To-Dos",
    description: "Onboarding and offboarding task board",
    href: "/checklist/todos",
    section: "People",
    icon: ListTodo,
    roles: ALL_STAFF,
    helpSlug: "employees",
  },
  {
    id: "leave",
    label: "Leave",
    description: "Request time off and approve team leave",
    href: "/leave",
    section: "Time & Leave",
    icon: CalendarOff,
    roles: ALL_STAFF,
    helpSlug: "leave",
  },
  {
    id: "attendance",
    label: "Attendance",
    description: "Check in/out and view attendance history",
    href: "/attendance",
    section: "Time & Leave",
    icon: Clock,
    roles: ALL_STAFF,
    helpSlug: "attendance",
  },
  {
    id: "attendance-devices",
    label: "Attendance Devices",
    description: "Kiosk and biometric device API keys",
    href: "/attendance/devices",
    section: "Time & Leave",
    icon: Router,
    roles: DEVICE_ADMIN_ROLES,
    helpSlug: "attendance-devices",
  },
  {
    id: "payroll",
    label: "Payroll",
    description: "Payslips, payroll runs, and salary records",
    href: "/payroll",
    section: "Time & Leave",
    icon: Wallet,
    roles: PAYROLL_VIEW_ROLES,
    helpSlug: "payroll",
  },
  {
    id: "performance",
    label: "Performance",
    description: "KPIs, review cycles, and appraisals",
    href: "/performance",
    section: "Talent",
    icon: Medal,
    roles: PERFORMANCE_VIEW_ROLES,
    helpSlug: "performance",
  },
  {
    id: "recruitment",
    label: "Jobs",
    description: "Open roles and job postings",
    href: "/recruitment",
    section: "Talent",
    icon: Briefcase,
    roles: RECRUITMENT_ROLES,
    helpSlug: "recruitment",
  },
  {
    id: "candidates",
    label: "Candidates",
    description: "Application pipeline and hiring stages",
    href: "/recruitment/candidates",
    section: "Talent",
    icon: UserSearch,
    roles: RECRUITMENT_ROLES,
    helpSlug: "recruitment",
  },
  {
    id: "interviews",
    label: "Interviews",
    description: "Schedule interviews and Google Calendar sync",
    href: "/recruitment/interviews",
    section: "Talent",
    icon: CalendarClock,
    roles: RECRUITMENT_ROLES,
    helpSlug: "recruitment",
  },
  {
    id: "announcements",
    label: "Announcements",
    description: "Company news and internal communications",
    href: "/announcements",
    section: "Workspace",
    icon: Megaphone,
    roles: ALL_STAFF,
    helpSlug: "announcements",
  },
  {
    id: "documents",
    label: "Documents",
    description: "HR document library and file links",
    href: "/documents",
    section: "Workspace",
    icon: FileText,
    roles: CONTENT_ADMIN_ROLES,
    helpSlug: "documents",
  },
  {
    id: "integrations",
    label: "Integrations",
    description: "Google Workspace and Zoho products",
    href: "/settings/integrations",
    section: "Administration",
    icon: Plug2,
    roles: INTEGRATION_ADMIN_ROLES,
    helpSlug: "integrations",
  },
  {
    id: "subscription",
    label: "Subscription",
    description: "Plans, billing, usage limits, and upgrades",
    href: "/settings/subscription",
    section: "Administration",
    icon: CreditCard,
    roles: [...SUBSCRIPTION_ADMIN_ROLES, "HR"],
    helpSlug: "settings",
  },
  {
    id: "settings",
    label: "Settings",
    description: "Profile, preferences, and account options",
    href: "/settings",
    section: "Administration",
    icon: Settings,
    roles: SETTINGS_ROLES,
    helpSlug: "settings",
  },
  {
    id: "help",
    label: "Help Center",
    description: "Guides, FAQs, and support",
    href: "/help",
    section: "Workspace",
    icon: CircleHelp,
    roles: CONTENT_ADMIN_ROLES,
  },
  {
    id: "api-docs",
    label: "API Documentation",
    description: "REST endpoints for attendance devices and integrations",
    href: "/docs",
    section: "Administration",
    icon: BookOpen,
    roles: [...INTEGRATION_ADMIN_ROLES, ...DEVICE_ADMIN_ROLES],
  },
];

export function getAppFeaturesForRole(role: Role): AppFeature[] {
  return appFeatures.filter((feature) => hasRole(role, feature.roles));
}

export function getAppFeaturesBySection(role: Role): Record<string, AppFeature[]> {
  const grouped: Record<string, AppFeature[]> = {};
  for (const feature of getAppFeaturesForRole(role)) {
    if (!grouped[feature.section]) grouped[feature.section] = [];
    grouped[feature.section].push(feature);
  }
  return grouped;
}
